/*
 * Copyright (c) 2010 Instrumentation Technologies
 * All Rights Reserved.
 *
 * $Id: i_application.idl 11980 2011-06-15 10:36:13Z matej.kenda $
 */

#ifndef _INET_APPLICATION_IDL
#define _INET_APPLICATION_IDL

#include "i_notification.idl"
#include "i_remote_node.idl"

#pragma prefix "i-tech.si"

module i_NET {
	
	interface Application
	{

	  /* Returns application interface version */	  
	  string       GetInterfaceVersion();

	  /* Get Remote node interface */
	  RemoteNode   GetRemoteNode(in Notification a_client);
	  void         ReleaseRemoteNode(in Notification a_client); 
	};
	
};

#endif  // _INET_APPLICATION_IDL
