// This file is generated by omniidl (C++ backend)- omniORB_4_1. Do not edit.
#ifndef __i__pingable_hh__
#define __i__pingable_hh__

#ifndef __CORBA_H_EXTERNAL_GUARD__
#include <omniORB4/CORBA.h>
#endif

#ifndef  USE_stub_in_nt_dll
# define USE_stub_in_nt_dll_NOT_DEFINED_i__pingable
#endif
#ifndef  USE_core_stub_in_nt_dll
# define USE_core_stub_in_nt_dll_NOT_DEFINED_i__pingable
#endif
#ifndef  USE_dyn_stub_in_nt_dll
# define USE_dyn_stub_in_nt_dll_NOT_DEFINED_i__pingable
#endif






#ifdef USE_stub_in_nt_dll
# ifndef USE_core_stub_in_nt_dll
#  define USE_core_stub_in_nt_dll
# endif
# ifndef USE_dyn_stub_in_nt_dll
#  define USE_dyn_stub_in_nt_dll
# endif
#endif

#ifdef _core_attr
# error "A local CPP macro _core_attr has already been defined."
#else
# ifdef  USE_core_stub_in_nt_dll
#  define _core_attr _OMNIORB_NTDLL_IMPORT
# else
#  define _core_attr
# endif
#endif

#ifdef _dyn_attr
# error "A local CPP macro _dyn_attr has already been defined."
#else
# ifdef  USE_dyn_stub_in_nt_dll
#  define _dyn_attr _OMNIORB_NTDLL_IMPORT
# else
#  define _dyn_attr
# endif
#endif





_CORBA_MODULE i_NET

_CORBA_MODULE_BEG

#ifndef __i__NET_mPingable__
#define __i__NET_mPingable__

  class Pingable;
  class _objref_Pingable;
  class _impl_Pingable;
  
  typedef _objref_Pingable* Pingable_ptr;
  typedef Pingable_ptr PingableRef;

  class Pingable_Helper {
  public:
    typedef Pingable_ptr _ptr_type;

    static _ptr_type _nil();
    static _CORBA_Boolean is_nil(_ptr_type);
    static void release(_ptr_type);
    static void duplicate(_ptr_type);
    static void marshalObjRef(_ptr_type, cdrStream&);
    static _ptr_type unmarshalObjRef(cdrStream&);
  };

  typedef _CORBA_ObjRef_Var<_objref_Pingable, Pingable_Helper> Pingable_var;
  typedef _CORBA_ObjRef_OUT_arg<_objref_Pingable,Pingable_Helper > Pingable_out;

#endif

  // interface Pingable
  class Pingable {
  public:
    // Declarations for this interface type.
    typedef Pingable_ptr _ptr_type;
    typedef Pingable_var _var_type;

    static _ptr_type _duplicate(_ptr_type);
    static _ptr_type _narrow(::CORBA::Object_ptr);
    static _ptr_type _unchecked_narrow(::CORBA::Object_ptr);
    
    static _ptr_type _nil();

    static inline void _marshalObjRef(_ptr_type, cdrStream&);

    static inline _ptr_type _unmarshalObjRef(cdrStream& s) {
      omniObjRef* o = omniObjRef::_unMarshal(_PD_repoId,s);
      if (o)
        return (_ptr_type) o->_ptrToObjRef(_PD_repoId);
      else
        return _nil();
    }

    static _core_attr const char* _PD_repoId;

    // Other IDL defined within this scope.
    
  };

  class _objref_Pingable :
    public virtual ::CORBA::Object,
    public virtual omniObjRef
  {
  public:
    ::CORBA::Boolean PingMe(Pingable_ptr a_ping, const char* a_cookie);
    void Ping();

    inline _objref_Pingable()  { _PR_setobj(0); }  // nil
    _objref_Pingable(omniIOR*, omniIdentity*);

  protected:
    virtual ~_objref_Pingable();

    
  private:
    virtual void* _ptrToObjRef(const char*);

    _objref_Pingable(const _objref_Pingable&);
    _objref_Pingable& operator = (const _objref_Pingable&);
    // not implemented

    friend class Pingable;
  };

  class _pof_Pingable : public _OMNI_NS(proxyObjectFactory) {
  public:
    inline _pof_Pingable() : _OMNI_NS(proxyObjectFactory)(Pingable::_PD_repoId) {}
    virtual ~_pof_Pingable();

    virtual omniObjRef* newObjRef(omniIOR*,omniIdentity*);
    virtual _CORBA_Boolean is_a(const char*) const;
  };

  class _impl_Pingable :
    public virtual omniServant
  {
  public:
    virtual ~_impl_Pingable();

    virtual ::CORBA::Boolean PingMe(Pingable_ptr a_ping, const char* a_cookie) = 0;
    virtual void Ping() = 0;
    
  public:  // Really protected, workaround for xlC
    virtual _CORBA_Boolean _dispatch(omniCallHandle&);

  private:
    virtual void* _ptrToInterface(const char*);
    virtual const char* _mostDerivedRepoId();
    
  };


  _CORBA_MODULE_VAR _dyn_attr const ::CORBA::TypeCode_ptr _tc_Pingable;

_CORBA_MODULE_END



_CORBA_MODULE POA_i_NET
_CORBA_MODULE_BEG

  class Pingable :
    public virtual i_NET::_impl_Pingable,
    public virtual ::PortableServer::ServantBase
  {
  public:
    virtual ~Pingable();

    inline ::i_NET::Pingable_ptr _this() {
      return (::i_NET::Pingable_ptr) _do_this(::i_NET::Pingable::_PD_repoId);
    }
  };

_CORBA_MODULE_END



_CORBA_MODULE OBV_i_NET
_CORBA_MODULE_BEG

_CORBA_MODULE_END





#undef _core_attr
#undef _dyn_attr

void operator<<=(::CORBA::Any& _a, i_NET::Pingable_ptr _s);
void operator<<=(::CORBA::Any& _a, i_NET::Pingable_ptr* _s);
_CORBA_Boolean operator>>=(const ::CORBA::Any& _a, i_NET::Pingable_ptr& _s);



inline void
i_NET::Pingable::_marshalObjRef(::i_NET::Pingable_ptr obj, cdrStream& s) {
  omniObjRef::_marshal(obj->_PR_getobj(),s);
}




#ifdef   USE_stub_in_nt_dll_NOT_DEFINED_i__pingable
# undef  USE_stub_in_nt_dll
# undef  USE_stub_in_nt_dll_NOT_DEFINED_i__pingable
#endif
#ifdef   USE_core_stub_in_nt_dll_NOT_DEFINED_i__pingable
# undef  USE_core_stub_in_nt_dll
# undef  USE_core_stub_in_nt_dll_NOT_DEFINED_i__pingable
#endif
#ifdef   USE_dyn_stub_in_nt_dll_NOT_DEFINED_i__pingable
# undef  USE_dyn_stub_in_nt_dll
# undef  USE_dyn_stub_in_nt_dll_NOT_DEFINED_i__pingable
#endif

#endif  // __i__pingable_hh__

