// This file is generated by omniidl (C++ backend)- omniORB_4_1. Do not edit.
#ifndef __i__remote__signal_hh__
#define __i__remote__signal_hh__

#ifndef __CORBA_H_EXTERNAL_GUARD__
#include <omniORB4/CORBA.h>
#endif

#ifndef  USE_stub_in_nt_dll
# define USE_stub_in_nt_dll_NOT_DEFINED_i__remote__signal
#endif
#ifndef  USE_core_stub_in_nt_dll
# define USE_core_stub_in_nt_dll_NOT_DEFINED_i__remote__signal
#endif
#ifndef  USE_dyn_stub_in_nt_dll
# define USE_dyn_stub_in_nt_dll_NOT_DEFINED_i__remote__signal
#endif



#ifndef __i__types_hh_EXTERNAL_GUARD__
#define __i__types_hh_EXTERNAL_GUARD__
#include "i_types.h"
#endif
#ifndef __i__signal__receiver_hh_EXTERNAL_GUARD__
#define __i__signal__receiver_hh_EXTERNAL_GUARD__
#include "i_signal_receiver.h"
#endif



#ifdef USE_stub_in_nt_dll
# ifndef USE_core_stub_in_nt_dll
#  define USE_core_stub_in_nt_dll
# endif
# ifndef USE_dyn_stub_in_nt_dll
#  define USE_dyn_stub_in_nt_dll
# endif
#endif

#ifdef _core_attr
# error "A local CPP macro _core_attr has already been defined."
#else
# ifdef  USE_core_stub_in_nt_dll
#  define _core_attr _OMNIORB_NTDLL_IMPORT
# else
#  define _core_attr
# endif
#endif

#ifdef _dyn_attr
# error "A local CPP macro _dyn_attr has already been defined."
#else
# ifdef  USE_dyn_stub_in_nt_dll
#  define _dyn_attr _OMNIORB_NTDLL_IMPORT
# else
#  define _dyn_attr
# endif
#endif





_CORBA_MODULE i_NET

_CORBA_MODULE_BEG

#ifndef __i__NET_mRemoteSignal__
#define __i__NET_mRemoteSignal__

  class RemoteSignal;
  class _objref_RemoteSignal;
  class _impl_RemoteSignal;
  
  typedef _objref_RemoteSignal* RemoteSignal_ptr;
  typedef RemoteSignal_ptr RemoteSignalRef;

  class RemoteSignal_Helper {
  public:
    typedef RemoteSignal_ptr _ptr_type;

    static _ptr_type _nil();
    static _CORBA_Boolean is_nil(_ptr_type);
    static void release(_ptr_type);
    static void duplicate(_ptr_type);
    static void marshalObjRef(_ptr_type, cdrStream&);
    static _ptr_type unmarshalObjRef(cdrStream&);
  };

  typedef _CORBA_ObjRef_Var<_objref_RemoteSignal, RemoteSignal_Helper> RemoteSignal_var;
  typedef _CORBA_ObjRef_OUT_arg<_objref_RemoteSignal,RemoteSignal_Helper > RemoteSignal_out;

#endif

  // interface RemoteSignal
  class RemoteSignal {
  public:
    // Declarations for this interface type.
    typedef RemoteSignal_ptr _ptr_type;
    typedef RemoteSignal_var _var_type;

    static _ptr_type _duplicate(_ptr_type);
    static _ptr_type _narrow(::CORBA::Object_ptr);
    static _ptr_type _unchecked_narrow(::CORBA::Object_ptr);
    
    static _ptr_type _nil();

    static inline void _marshalObjRef(_ptr_type, cdrStream&);

    static inline _ptr_type _unmarshalObjRef(cdrStream& s) {
      omniObjRef* o = omniObjRef::_unMarshal(_PD_repoId,s);
      if (o)
        return (_ptr_type) o->_ptrToObjRef(_PD_repoId);
      else
        return _nil();
    }

    static _core_attr const char* _PD_repoId;

    // Other IDL defined within this scope.
    
  };

  class _objref_RemoteSignal :
    public virtual ::CORBA::Object,
    public virtual omniObjRef
  {
  public:
    ::CORBA::ULong DodReadI8(SignalReceiver_ptr a_rec, ::CORBA::ULongLong a_position, ::CORBA::ULong a_len, Int8Buffer_out a_buf, SignalMeta_out a_meta);
    ::CORBA::ULong DodReadUI8(SignalReceiver_ptr a_rec, ::CORBA::ULongLong a_position, ::CORBA::ULong a_len, UInt8Buffer_out a_buf, SignalMeta_out a_meta);
    ::CORBA::ULong DodReadI16(SignalReceiver_ptr a_rec, ::CORBA::ULongLong a_position, ::CORBA::ULong a_len, Int16Buffer_out a_buf, SignalMeta_out a_meta);
    ::CORBA::ULong DodReadUI16(SignalReceiver_ptr a_rec, ::CORBA::ULongLong a_position, ::CORBA::ULong a_len, UInt16Buffer_out a_buf, SignalMeta_out a_meta);
    ::CORBA::ULong DodReadI32(SignalReceiver_ptr a_rec, ::CORBA::ULongLong a_position, ::CORBA::ULong a_len, Int32Buffer_out a_buf, SignalMeta_out a_meta);
    ::CORBA::ULong DodReadUI32(SignalReceiver_ptr a_rec, ::CORBA::ULongLong a_position, ::CORBA::ULong a_len, UInt32Buffer_out a_buf, SignalMeta_out a_meta);
    ::CORBA::ULong DodReadI64(SignalReceiver_ptr a_rec, ::CORBA::ULongLong a_position, ::CORBA::ULong a_len, Int64Buffer_out a_buf, SignalMeta_out a_meta);
    ::CORBA::ULong DodReadUI64(SignalReceiver_ptr a_rec, ::CORBA::ULongLong a_position, ::CORBA::ULong a_len, UInt64Buffer_out a_buf, SignalMeta_out a_meta);
    ::CORBA::ULong DodReadFloat(SignalReceiver_ptr a_rec, ::CORBA::ULongLong a_position, ::CORBA::ULong a_len, FloatBuffer_out a_buf, SignalMeta_out a_meta);
    ::CORBA::ULong DodReadDouble(SignalReceiver_ptr a_rec, ::CORBA::ULongLong a_position, ::CORBA::ULong a_len, DoubleBuffer_out a_buf, SignalMeta_out a_meta);
    ::CORBA::ULong RegisterReceiver(SignalReceiver_ptr a_rec, ::CORBA::ULong a_accessMode, ::CORBA::ULong a_readSize, ::CORBA::LongLong a_readOffset, ::CORBA::ULong a_qcapacity);
    void UnregisterReceiver(SignalReceiver_ptr a_rec);
    SignalStats* GetStatistics(SignalReceiver_ptr a_rec);

    inline _objref_RemoteSignal()  { _PR_setobj(0); }  // nil
    _objref_RemoteSignal(omniIOR*, omniIdentity*);

  protected:
    virtual ~_objref_RemoteSignal();

    
  private:
    virtual void* _ptrToObjRef(const char*);

    _objref_RemoteSignal(const _objref_RemoteSignal&);
    _objref_RemoteSignal& operator = (const _objref_RemoteSignal&);
    // not implemented

    friend class RemoteSignal;
  };

  class _pof_RemoteSignal : public _OMNI_NS(proxyObjectFactory) {
  public:
    inline _pof_RemoteSignal() : _OMNI_NS(proxyObjectFactory)(RemoteSignal::_PD_repoId) {}
    virtual ~_pof_RemoteSignal();

    virtual omniObjRef* newObjRef(omniIOR*,omniIdentity*);
    virtual _CORBA_Boolean is_a(const char*) const;
  };

  class _impl_RemoteSignal :
    public virtual omniServant
  {
  public:
    virtual ~_impl_RemoteSignal();

    virtual ::CORBA::ULong DodReadI8(SignalReceiver_ptr a_rec, ::CORBA::ULongLong a_position, ::CORBA::ULong a_len, Int8Buffer_out a_buf, SignalMeta_out a_meta) = 0;
    virtual ::CORBA::ULong DodReadUI8(SignalReceiver_ptr a_rec, ::CORBA::ULongLong a_position, ::CORBA::ULong a_len, UInt8Buffer_out a_buf, SignalMeta_out a_meta) = 0;
    virtual ::CORBA::ULong DodReadI16(SignalReceiver_ptr a_rec, ::CORBA::ULongLong a_position, ::CORBA::ULong a_len, Int16Buffer_out a_buf, SignalMeta_out a_meta) = 0;
    virtual ::CORBA::ULong DodReadUI16(SignalReceiver_ptr a_rec, ::CORBA::ULongLong a_position, ::CORBA::ULong a_len, UInt16Buffer_out a_buf, SignalMeta_out a_meta) = 0;
    virtual ::CORBA::ULong DodReadI32(SignalReceiver_ptr a_rec, ::CORBA::ULongLong a_position, ::CORBA::ULong a_len, Int32Buffer_out a_buf, SignalMeta_out a_meta) = 0;
    virtual ::CORBA::ULong DodReadUI32(SignalReceiver_ptr a_rec, ::CORBA::ULongLong a_position, ::CORBA::ULong a_len, UInt32Buffer_out a_buf, SignalMeta_out a_meta) = 0;
    virtual ::CORBA::ULong DodReadI64(SignalReceiver_ptr a_rec, ::CORBA::ULongLong a_position, ::CORBA::ULong a_len, Int64Buffer_out a_buf, SignalMeta_out a_meta) = 0;
    virtual ::CORBA::ULong DodReadUI64(SignalReceiver_ptr a_rec, ::CORBA::ULongLong a_position, ::CORBA::ULong a_len, UInt64Buffer_out a_buf, SignalMeta_out a_meta) = 0;
    virtual ::CORBA::ULong DodReadFloat(SignalReceiver_ptr a_rec, ::CORBA::ULongLong a_position, ::CORBA::ULong a_len, FloatBuffer_out a_buf, SignalMeta_out a_meta) = 0;
    virtual ::CORBA::ULong DodReadDouble(SignalReceiver_ptr a_rec, ::CORBA::ULongLong a_position, ::CORBA::ULong a_len, DoubleBuffer_out a_buf, SignalMeta_out a_meta) = 0;
    virtual ::CORBA::ULong RegisterReceiver(SignalReceiver_ptr a_rec, ::CORBA::ULong a_accessMode, ::CORBA::ULong a_readSize, ::CORBA::LongLong a_readOffset, ::CORBA::ULong a_qcapacity) = 0;
    virtual void UnregisterReceiver(SignalReceiver_ptr a_rec) = 0;
    virtual SignalStats* GetStatistics(SignalReceiver_ptr a_rec) = 0;
    
  public:  // Really protected, workaround for xlC
    virtual _CORBA_Boolean _dispatch(omniCallHandle&);

  private:
    virtual void* _ptrToInterface(const char*);
    virtual const char* _mostDerivedRepoId();
    
  };


  _CORBA_MODULE_VAR _dyn_attr const ::CORBA::TypeCode_ptr _tc_RemoteSignal;

_CORBA_MODULE_END



_CORBA_MODULE POA_i_NET
_CORBA_MODULE_BEG

  class RemoteSignal :
    public virtual i_NET::_impl_RemoteSignal,
    public virtual ::PortableServer::ServantBase
  {
  public:
    virtual ~RemoteSignal();

    inline ::i_NET::RemoteSignal_ptr _this() {
      return (::i_NET::RemoteSignal_ptr) _do_this(::i_NET::RemoteSignal::_PD_repoId);
    }
  };

_CORBA_MODULE_END



_CORBA_MODULE OBV_i_NET
_CORBA_MODULE_BEG

_CORBA_MODULE_END





#undef _core_attr
#undef _dyn_attr

void operator<<=(::CORBA::Any& _a, i_NET::RemoteSignal_ptr _s);
void operator<<=(::CORBA::Any& _a, i_NET::RemoteSignal_ptr* _s);
_CORBA_Boolean operator>>=(const ::CORBA::Any& _a, i_NET::RemoteSignal_ptr& _s);



inline void
i_NET::RemoteSignal::_marshalObjRef(::i_NET::RemoteSignal_ptr obj, cdrStream& s) {
  omniObjRef::_marshal(obj->_PR_getobj(),s);
}




#ifdef   USE_stub_in_nt_dll_NOT_DEFINED_i__remote__signal
# undef  USE_stub_in_nt_dll
# undef  USE_stub_in_nt_dll_NOT_DEFINED_i__remote__signal
#endif
#ifdef   USE_core_stub_in_nt_dll_NOT_DEFINED_i__remote__signal
# undef  USE_core_stub_in_nt_dll
# undef  USE_core_stub_in_nt_dll_NOT_DEFINED_i__remote__signal
#endif
#ifdef   USE_dyn_stub_in_nt_dll_NOT_DEFINED_i__remote__signal
# undef  USE_dyn_stub_in_nt_dll
# undef  USE_dyn_stub_in_nt_dll_NOT_DEFINED_i__remote__signal
#endif

#endif  // __i__remote__signal_hh__

