// This file is generated by omniidl (C++ backend)- omniORB_4_1. Do not edit.
#ifndef __i__application_hh__
#define __i__application_hh__

#ifndef __CORBA_H_EXTERNAL_GUARD__
#include <omniORB4/CORBA.h>
#endif

#ifndef  USE_stub_in_nt_dll
# define USE_stub_in_nt_dll_NOT_DEFINED_i__application
#endif
#ifndef  USE_core_stub_in_nt_dll
# define USE_core_stub_in_nt_dll_NOT_DEFINED_i__application
#endif
#ifndef  USE_dyn_stub_in_nt_dll
# define USE_dyn_stub_in_nt_dll_NOT_DEFINED_i__application
#endif



#ifndef __i__types_hh_EXTERNAL_GUARD__
#define __i__types_hh_EXTERNAL_GUARD__
#include "i_types.h"
#endif
#ifndef __i__notification_hh_EXTERNAL_GUARD__
#define __i__notification_hh_EXTERNAL_GUARD__
#include "i_notification.h"
#endif
#ifndef __i__signal__receiver_hh_EXTERNAL_GUARD__
#define __i__signal__receiver_hh_EXTERNAL_GUARD__
#include "i_signal_receiver.h"
#endif
#ifndef __i__remote__signal_hh_EXTERNAL_GUARD__
#define __i__remote__signal_hh_EXTERNAL_GUARD__
#include "i_remote_signal.h"
#endif
#ifndef __i__remote__node_hh_EXTERNAL_GUARD__
#define __i__remote__node_hh_EXTERNAL_GUARD__
#include "i_remote_node.h"
#endif



#ifdef USE_stub_in_nt_dll
# ifndef USE_core_stub_in_nt_dll
#  define USE_core_stub_in_nt_dll
# endif
# ifndef USE_dyn_stub_in_nt_dll
#  define USE_dyn_stub_in_nt_dll
# endif
#endif

#ifdef _core_attr
# error "A local CPP macro _core_attr has already been defined."
#else
# ifdef  USE_core_stub_in_nt_dll
#  define _core_attr _OMNIORB_NTDLL_IMPORT
# else
#  define _core_attr
# endif
#endif

#ifdef _dyn_attr
# error "A local CPP macro _dyn_attr has already been defined."
#else
# ifdef  USE_dyn_stub_in_nt_dll
#  define _dyn_attr _OMNIORB_NTDLL_IMPORT
# else
#  define _dyn_attr
# endif
#endif





_CORBA_MODULE i_NET

_CORBA_MODULE_BEG

#ifndef __i__NET_mApplication__
#define __i__NET_mApplication__

  class Application;
  class _objref_Application;
  class _impl_Application;
  
  typedef _objref_Application* Application_ptr;
  typedef Application_ptr ApplicationRef;

  class Application_Helper {
  public:
    typedef Application_ptr _ptr_type;

    static _ptr_type _nil();
    static _CORBA_Boolean is_nil(_ptr_type);
    static void release(_ptr_type);
    static void duplicate(_ptr_type);
    static void marshalObjRef(_ptr_type, cdrStream&);
    static _ptr_type unmarshalObjRef(cdrStream&);
  };

  typedef _CORBA_ObjRef_Var<_objref_Application, Application_Helper> Application_var;
  typedef _CORBA_ObjRef_OUT_arg<_objref_Application,Application_Helper > Application_out;

#endif

  // interface Application
  class Application {
  public:
    // Declarations for this interface type.
    typedef Application_ptr _ptr_type;
    typedef Application_var _var_type;

    static _ptr_type _duplicate(_ptr_type);
    static _ptr_type _narrow(::CORBA::Object_ptr);
    static _ptr_type _unchecked_narrow(::CORBA::Object_ptr);
    
    static _ptr_type _nil();

    static inline void _marshalObjRef(_ptr_type, cdrStream&);

    static inline _ptr_type _unmarshalObjRef(cdrStream& s) {
      omniObjRef* o = omniObjRef::_unMarshal(_PD_repoId,s);
      if (o)
        return (_ptr_type) o->_ptrToObjRef(_PD_repoId);
      else
        return _nil();
    }

    static _core_attr const char* _PD_repoId;

    // Other IDL defined within this scope.
    
  };

  class _objref_Application :
    public virtual ::CORBA::Object,
    public virtual omniObjRef
  {
  public:
    char* GetInterfaceVersion();
    RemoteNode_ptr GetRemoteNode(Notification_ptr a_client);
    void ReleaseRemoteNode(Notification_ptr a_client);

    inline _objref_Application()  { _PR_setobj(0); }  // nil
    _objref_Application(omniIOR*, omniIdentity*);

  protected:
    virtual ~_objref_Application();

    
  private:
    virtual void* _ptrToObjRef(const char*);

    _objref_Application(const _objref_Application&);
    _objref_Application& operator = (const _objref_Application&);
    // not implemented

    friend class Application;
  };

  class _pof_Application : public _OMNI_NS(proxyObjectFactory) {
  public:
    inline _pof_Application() : _OMNI_NS(proxyObjectFactory)(Application::_PD_repoId) {}
    virtual ~_pof_Application();

    virtual omniObjRef* newObjRef(omniIOR*,omniIdentity*);
    virtual _CORBA_Boolean is_a(const char*) const;
  };

  class _impl_Application :
    public virtual omniServant
  {
  public:
    virtual ~_impl_Application();

    virtual char* GetInterfaceVersion() = 0;
    virtual RemoteNode_ptr GetRemoteNode(Notification_ptr a_client) = 0;
    virtual void ReleaseRemoteNode(Notification_ptr a_client) = 0;
    
  public:  // Really protected, workaround for xlC
    virtual _CORBA_Boolean _dispatch(omniCallHandle&);

  private:
    virtual void* _ptrToInterface(const char*);
    virtual const char* _mostDerivedRepoId();
    
  };


  _CORBA_MODULE_VAR _dyn_attr const ::CORBA::TypeCode_ptr _tc_Application;

_CORBA_MODULE_END



_CORBA_MODULE POA_i_NET
_CORBA_MODULE_BEG

  class Application :
    public virtual i_NET::_impl_Application,
    public virtual ::PortableServer::ServantBase
  {
  public:
    virtual ~Application();

    inline ::i_NET::Application_ptr _this() {
      return (::i_NET::Application_ptr) _do_this(::i_NET::Application::_PD_repoId);
    }
  };

_CORBA_MODULE_END



_CORBA_MODULE OBV_i_NET
_CORBA_MODULE_BEG

_CORBA_MODULE_END





#undef _core_attr
#undef _dyn_attr

void operator<<=(::CORBA::Any& _a, i_NET::Application_ptr _s);
void operator<<=(::CORBA::Any& _a, i_NET::Application_ptr* _s);
_CORBA_Boolean operator>>=(const ::CORBA::Any& _a, i_NET::Application_ptr& _s);



inline void
i_NET::Application::_marshalObjRef(::i_NET::Application_ptr obj, cdrStream& s) {
  omniObjRef::_marshal(obj->_PR_getobj(),s);
}




#ifdef   USE_stub_in_nt_dll_NOT_DEFINED_i__application
# undef  USE_stub_in_nt_dll
# undef  USE_stub_in_nt_dll_NOT_DEFINED_i__application
#endif
#ifdef   USE_core_stub_in_nt_dll_NOT_DEFINED_i__application
# undef  USE_core_stub_in_nt_dll
# undef  USE_core_stub_in_nt_dll_NOT_DEFINED_i__application
#endif
#ifdef   USE_dyn_stub_in_nt_dll_NOT_DEFINED_i__application
# undef  USE_dyn_stub_in_nt_dll
# undef  USE_dyn_stub_in_nt_dll_NOT_DEFINED_i__application
#endif

#endif  // __i__application_hh__

